import { cookieStorage, createStorage } from 'wagmi'
import { WagmiAdapter } from '@reown/appkit-adapter-wagmi'
import { mainnet, polygon, bsc, arbitrum, avalanche, base } from '@reown/appkit/networks'
import type { Chain } from 'viem'

// Read Project ID from environment variables
export const projectId = process.env.NEXT_PUBLIC_PROJECT_ID

// Ensure Project ID is defined at build time
if (!projectId) {
  throw new Error('NEXT_PUBLIC_PROJECT_ID is not defined. Please set it in .env.local')
}

// Minimal networks configuration - just the essentials
const networks: [Chain, ...Chain[]] = [
  mainnet,
  {
    ...mainnet,
    id: 369,
    name: 'PulseChain',
    nativeCurrency: { name: 'Pulse', symbol: 'PLS', decimals: 18 },
    rpcUrls: { 
      default: { http: ['https://rpc.pulsechain.com'] },
      public: { http: ['https://rpc.pulsechain.com'] }
    },
    blockExplorers: { 
      default: { 
        name: 'PulseScan', 
        url: 'https://scan.pulsechain.com',
        apiUrl: 'https://scan.pulsechain.com/api'
      } 
    },
    contracts: {
      multicall3: {
        address: '0xca11bde05977b3631167028862be2a173976ca11',
        blockCreated: 1
      }
    }
  },
  polygon,
  bsc,
  arbitrum,
  avalanche,
  base
]

// Create the Wagmi adapter instance
export const wagmiAdapter = new WagmiAdapter({
  storage: createStorage({ storage: cookieStorage }),
  ssr: true,
  projectId,
  networks,
})

// Export the Wagmi config generated by the adapter
export const config = wagmiAdapter.wagmiConfig

// Export networks for AppKit configuration
export { networks } 